applications:
    spajxo-cz:
        type: 'php:8.5'

        runtime:
            extensions:
                - apcu
                - ctype
                - iconv
                - mbstring
                - sodium
                - intl

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    expires: 1h
                    allow: true
                "/assets":
                    root: "public/assets"
                    expires: 1y
                    passthru: false
                    allow: true
                "/favicon.ico":
                    allow: true
                    expires: 1w

        variables:
            env:
                APP_ENV: prod
            php:
                opcache.preload: /app/config/preload.php
                opcache.preload_user: "web"
                opcache.memory_consumption: 256
                opcache.max_accelerated_files: 20000
                realpath_cache_size: 4096K
                realpath_cache_ttl: 600
                display_errors: "Off"
                expose_php: "Off"
                memory_limit: 256M
                post_max_size: 16M
                upload_max_filesize: 16M

        build:
            flavor: none

        mounts:
            "/var": { source: "storage", source_path: "var" }

        hooks:
            build: |
                set -e
                composer install --no-dev --optimize-autoloader --no-interaction --classmap-authoritative
                php bin/console tailwind:build --minify
                php bin/console asset-map:compile
            deploy: |
                set -e
                php bin/console cache:clear

routes:
    "https://{default}/":
        type: upstream
        upstream: "spajxo-cz:http"
        cache:
            enabled: true
            default_ttl: 600
            cookies: ['/^sf_.*/']
            headers: ['Accept', 'Accept-Language']

    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"
