applications:
    spajxo-cz:
        type: 'php:8.5'

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"

        variables:
            env:
                APP_ENV: prod

        build:
            flavor: none

        mounts:
            "/var": { source: "storage", source_path: "var" }

        hooks:
            build: |
                set -e
                composer install --no-dev --optimize-autoloader --no-interaction
                php bin/console tailwind:build --minify
                php bin/console asset-map:compile
            deploy: |
                set -e
                php bin/console cache:clear

routes:
    "https://{default}/":
        type: upstream
        upstream: "spajxo-cz:http"

    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"
